version: "3.9"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - type: bind
        source: ./app/src
        target: /app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    restart: unless-stopped
  db:
    image: mysql:5.7
    env_file:
      - ./db/.env
    restart: always
    volumes:
      - type: volume
        source: dbdev
        target: /var/lib/mysql
volumes:
  dbdev:
 
  

